name: Deploy Smart Contract

on:
  workflow_dispatch: # Σας επιτρέπει να το τρέχετε χειροκίνητα

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Deploy Script
        env:
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
        run: node deploy.js
